### ISSUE TITLE
alminer.target needs a list

### ISSUE THREAD

**Issue by teuben** [emerge-erc/ALminer#1]
why not allow alminer.target() to also just use a string, instead of forcing one to use    (['blabla'])   , so many non-alpha's in a row makes my fingers dizzy :-)

**Comment by aida-ahmadi** [comment]
Hi Peter, thanks for using ALminer and for your suggestion. I have made the change to allow `alminer.target` to accept a string as well as a list of strings. So both

`alminer.target(['M17', 'M33']` 

and

`alminer.target('M17')`
`alminer.target('M33')`

will work. 

I hope that's the change you were requesting 🙂

**Comment by teuben** [comment]
perfect!
