### ISSUE TITLE
is actually alminer.CO_lines giving CO lines?

### ISSUE THREAD

**Issue by alessandropeca** [emerge-erc/ALminer#6]
Dear,

I am confused about the documentation. Is alminer.CO_lines giving the observation in which the CO lines may be detected, or where the CO line frequencies were observed, and then there may be some emission line (but at the time, may be not)?

**Comment by aida-ahmadi** [comment]
Dear Alessandro, 

`alminer.CO_lines` determines whether the frequencies of CO lines (and its 13CO and C18O isotopologues) are covered in a given observation. We cannot know whether lines are detected without downloading the data, so ALminer always determines whether frequencies are covered/observed and not whether they are detected. 

The API documentation states this correctly, I believe: https://alminer.readthedocs.io/en/latest/pages/api.html#alminer.CO_lines

I hope this helps clarify things =)

**Comment by alessandropeca** [comment]
Now it's clear, thank you! The documentation says that `alminer.CO_lines` returns a dataframe `containing all observations of (redshifted) CO, 13CO, and C18O lines.` so, at least to me, was not crystal clear.

Since in the ALMA archive, there is the automated detection of emission lines by ADMIT, I thought that maybe, alminer could have been related to that.

**Comment by aida-ahmadi** [comment]
Thanks for pointing out that this part of the documentation was confusing. I will close this ticket now, but please feel free to open another one if you have other questions.
